### ISSUE TITLE
No build instructions

### ISSUE THREAD

**Issue by L1Q** [peterhellberg/pixel-experiments#1]
'go get' only installs modules in $HOME/go
How does one build and run anything from this repo?

Was looking to check out starfield experiment

**Comment by L1Q** [comment]
I'm on linux, installed ``go`` version ``2:1.16.5-1`` which according to package manager takes ``597.76 MiB`` on my drive.
Created empty directory for this experiments project, run ``go get -u -d github.com/peterhellberg/pixel-experiments`` in the empty directory as recommended.
go installs the package and dependencies in ``~/go`` anyway. my directory remains empty
``~/go`` is now ``133 MiB``

What do I do next to run an experiment?

**Comment by peterhellberg** [comment]
@L1Q Hello, this project is a bunch of separate experiments and not really working out of the box these days (due to not being organized into a module)

To try out the starfield experiment you should be able to do something like:

```
git clone git@github.com:peterhellberg/pixel-experiments.git
cd pixel-experiments/starfield/
go mod init pixel-experiments/starfield
go get github.com/faiface/pixel@latest
go get github.com/faiface/glhf@latest
go get github.com/go-gl/glfw/v3.3/glfw@latest
go run starfield.go
```

(Increase speed with up arrow, stop with space)

**Comment by L1Q** [comment]
Thanks! These instructions worked flawlessly!
